version: "3.8"

services:
  publisher:
    build: ./src/ml_container
    container_name: publisher
    ports:
      - "5555:5555"
    networks:
      - app_network

  motor_container:
    build: ./src/motor_container
    container_name: motor_container
    depends_on:
      - publisher
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
