version: "3.8"
services:
  ml_container:
    build: ./src/ml_container
    ipc: "host"  # Enable IPC communication
    volumes:
      - /tmp:/tmp  # Share IPC socket

  motor_container:
    build: ./src/motor_container
    ipc: "host"  # Enable IPC communication
    volumes:
      - /tmp:/tmp  # Share IPC socket
